### ISSUE TITLE
Exception Value: 'NoneType' object has no attribute 'year'

### ISSUE THREAD

**Issue by omercnet** [PetrDlouhy/django-admin-charts#19] opened 2020-08-09 09:27 UTC
First item in the series has a `None` for a key, ideas what could cause this?

https://dpaste.com/2MQW3YF43

*Local vars*:
```
__class__ | <class 'admin_tools_stats.views.ChartDataView'>
-- | --
args | ()
choices | {}
context | {'chart_type': 'discreteBarChart',  'view': <admin_tools_stats.views.ChartDataView object at 0x10fe0f850>}
criteria | None
dashboard_stats | <DashboardStats: user_graph>
graph_key | 'user_graph'
interval | 'days'
kwargs | {}
names | {}
self | <admin_tools_stats.views.ChartDataView object at 0x10fe0f850>
serie_i_map | OrderedDict()
series | {None: {'': 1},  datetime.datetime(2020, 7, 9, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 10, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 11, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 12, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 13, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 14, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 15, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 16, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 17, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 18, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 19, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 20, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 21, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 22, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 23, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 24, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 25, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 26, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 27, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 28, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 29, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 30, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 7, 31, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 8, 1, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 8, 2, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 8, 3, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 8, 4, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 8, 5, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 8, 6, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 8, 7, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 8, 8, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)]),  datetime.datetime(2020, 8, 9, 0, 0, tzinfo=<UTC>): OrderedDict([('', 0)])}
time_since | datetime.datetime(2020, 7, 9, 0, 0)
time_until | datetime.datetime(2020, 8, 9, 0, 0)
xdata | []
ydata_serie | {}

```

**Comment by PetrDlouhy** [comment] 2020-10-05 06:29
@omercnet I am not sure and the `dpaste` link doesn't work now. But I would try to look to the output of `get_time_series()` function in `models.py` package.

**Comment by WhiteRose7-pretty** [comment] 2020-10-16 22:32
Hello @PetrDlouhy 
I have installed and and running your demo project.
But chart is not displaying in admin page, so I checked console.
There was error.
 AttributeError at /admin_tools_stats/chart_data/user_graph/
'NoneType' object has no attribute 'year'
Thank you in advance.
Valya.

**Comment by kingraphaii** [comment] 2021-02-20 18:03
Getting the same error. Did you manage to solve this @WhiteRose7-pretty ?

**Comment by PetrDlouhy** [comment] 2021-02-20 18:13
@kingraphaii Can you please post some more info about this?
Like full traceback or where does the error pop up?

**Comment by PetrDlouhy** [comment] 2021-02-20 18:16
Generally it can be caused by problems with JSONfield (#26 and #23) or some problem with the `Date field name`.

Django version would be also very hepfull.

**Comment by kingraphaii** [comment] 2021-02-20 18:30
Hi Petr. I was just trying out the package on `Django==3.1.6`. The error happens when I try to preview a chart. Here is the traceback:

```
Traceback (most recent call last):
  File "/home/redgren/.venvs/gwd/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/redgren/.venvs/gwd/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/redgren/.venvs/gwd/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/redgren/.venvs/gwd/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/redgren/.venvs/gwd/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/redgren/.venvs/gwd/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/redgren/.venvs/gwd/lib/python3.8/site-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/home/redgren/.venvs/gwd/lib/python3.8/site-packages/admin_tools_stats/views.py", line 82, in get_context_data
    for date in sorted(series.keys(), key=lambda d: datetime(d.year, d.month, d.day, getattr(d, 'hour', 0))):
  File "/home/redgren/.venvs/gwd/lib/python3.8/site-packages/admin_tools_stats/views.py", line 82, in <lambda>
    for date in sorted(series.keys(), key=lambda d: datetime(d.year, d.month, d.day, getattr(d, 'hour', 0))):

Exception Type: AttributeError at /admin_tools_stats/chart_data/top_customers/
Exception Value: 'NoneType' object has no attribute 'year'
```
From what I've seen so far, one or more elements in `sorted.keys()` are `None`

**Comment by PetrDlouhy** [comment] 2021-02-20 18:53
Do you have some `None` values in your `Date field name` field?

**Comment by kingraphaii** [comment] 2021-02-20 19:26
No, the field is does not have null values. It's defined as `date_placed = models.DateTimeField()`

**Comment by WhiteRose7-pretty** [comment] 2021-02-20 20:19
> Getting the same error. Did you manage to solve this @WhiteRose7-pretty ?

Yes, by using PostgreSQL as db, I solved the issue.

**Comment by PetrDlouhy** [comment] 2021-02-21 11:22
I have started experimenting with MySQL support in the branch https://github.com/PetrDlouhy/django-admin-charts/tree/mysql. I make the tests mostly working, but before I bumped to this issue, I find out, the Trunc DB function (https://docs.djangoproject.com/en/3.1/ref/models/database-functions/#trunc) doesn't work under MySQL.
I don't know why, it is not described in the docs, but it returns untruncated values.

Without working Trunc, it would be quite hard to make `django-admin-charts` effectively  under MySQL. So before fixing this issue, the Trunc should be resolved somehow.

**Comment by PetrDlouhy** [comment] 2021-02-21 11:52
I figured out what was the problem - the `kind` parameter should get values like `day`, but it was getting `days`, which works under Postgres, but not MySQL.

@kingraphaii Can you please test the branch `mysql` now? I am not sure if it is the same problem, but at least the tests are now passing.

**Comment by PetrDlouhy** [comment] 2022-03-17 08:33
This issue should be fixed in the newer versions of `django-admin-charts`. If the problems remain, please reopen.

**Closed by PetrDlouhy** 2022-03-17 08:33 UTC
